// wa1_drill.ts (GENERATED by emit_ts.py) - drill-only sets from wa1_zh_drill.json; never merged into WA1_ZH_PRACTICE
import type { ZhPracticeSet } from "./schema";

export const WA1_ZH_DRILL: ZhPracticeSet[] =
/* WA1_ZH_DRILL_JSON_BEGIN */
[
 {
  "setId": "ZD01",
  "theme": "drill yufa",
  "track": "HCL",
  "band": "mid",
  "seedSources": [
   "gen:yufa"
  ],
  "plan": [
   {
    "type": "VocabMcq",
    "marks": 12,
    "items": [
     {
      "id": "ZD01_C1",
      "topic": "VocabMcq",
      "sentence": "弟弟______作业写完了，才出去和朋友踢球。",
      "options": [
       "把",
       "对",
       "跟",
       "给"
      ],
      "answer": 0,
      "lesson": 1,
      "skill": "yufa",
      "explain": {
       "why": "“把作业写完了”是把字句，表示对”作业”这个对象完成了”写完”这个动作，句式完整通顺。",
       "distractors": [
        "✓ 正确答案：把＋名词＋动词，是处置式把字句，表示对某物做了某动作。",
        "“对作业写完了”不通，“对”后面要接的是态度或兴趣，不能这样用。",
        "“跟作业写完了”不通，“跟”表示和某人一起，不用在物品前。",
        "“给作业写完了”不通，“给”表示给予，不用在这里。"
       ],
       "trapType": "yufa",
       "memoryTip": "把字句公式：把＋（东西）＋动词＋结果补语。看到”写完””做好””吃光”这类结果，考虑用”把”。"
      },
      "explanation": "“把作业写完了”是典型的把字句：把＋受影响的东西（作业）＋动词＋结果（写完了）。\n其余三个不对：对后面要接态度或兴趣（对画画的兴趣）；跟表示和某人一起（跟我去）；给表示给予（给我一本书）。\n【语法的方法】句子里有明确的受影响的东西和结果动词，要优先考虑把字句，填”把”。",
      "sentence_en": "Little brother ___ (used 把) his homework finished first, then went out to play football with friends.",
      "hints": [
       "The sentence shows that homework was completed before going out. Which word turns this into a 把-sentence, showing that something was dealt with?"
      ],
      "keywords": [
       {
        "w": "把",
        "py": "bǎ",
        "en": "disposal marker"
       },
       {
        "w": "作业",
        "py": "zuòyè",
        "en": "homework"
       },
       {
        "w": "才",
        "py": "cái",
        "en": "only then"
       }
      ],
      "explanation_en": "This is a 把-sentence: 把 + object (作业) + verb + result (写完了). It shows that the homework was dealt with and finished. 对, 跟 and 给 do not fit this pattern."
     },
     {
      "id": "ZD01_C2",
      "topic": "VocabMcq",
      "sentence": "姐姐______妈妈一起去市场买菜，买了很多新鲜的蔬菜。",
      "options": [
       "对",
       "把",
       "跟",
       "被"
      ],
      "answer": 2,
      "lesson": 1,
      "skill": "yufa",
      "explain": {
       "why": "“跟妈妈一起”是固定句式，表示和某人一起做某事，“跟妈妈一起去市场”意思通顺。",
       "distractors": [
        "“对妈妈一起去市场”不通，“对”表示态度方向，不表示陪伴。",
        "“把妈妈一起去市场”不通，“把”是处置式，不用在这里。",
        "✓ 正确答案：跟＋人＋一起＋动词，表示和某人一起做某事。",
        "“被妈妈一起去市场”不通，“被”是被动句，表示被某人做了某事，不合这里。"
       ],
       "trapType": "yufa",
       "memoryTip": "固定句式：跟＋（人）＋一起＋动词。看到”一起”，前面找”跟”。"
      },
      "explanation": "“跟……一起”是固定搭配，表示和某人共同做一件事。\n另外三个不对：对表示方向或态度（对我说）；把字句处置某物（把书拿来）；被字句表示被动（被老师表扬）。\n【语法的方法】看到”一起”，往前找”跟”，两个词常常配对出现。",
      "sentence_en": "Elder sister went to the market ___ (with) mum to buy vegetables and bought a lot of fresh produce.",
      "hints": [
       "The sentence says they went together. Which word means 'together with someone' and pairs with 一起?"
      ],
      "keywords": [
       {
        "w": "跟",
        "py": "gēn",
        "en": "with; together with"
       },
       {
        "w": "一起",
        "py": "yīqǐ",
        "en": "together"
       },
       {
        "w": "新鲜",
        "py": "xīnxiān",
        "en": "fresh"
       }
      ],
      "explanation_en": "跟……一起 is a fixed pattern meaning 'together with someone'. So 跟妈妈一起去 means 'went with mum'. When you see 一起, look for 跟 before the person."
     },
     {
      "id": "ZD01_C3",
      "topic": "VocabMcq",
      "sentence": "这本故事书______老师借给小明的，他要好好爱惜。",
      "options": [
       "把",
       "跟",
       "对",
       "是"
      ],
      "answer": 3,
      "lesson": 2,
      "skill": "yufa",
      "explain": {
       "why": "“是……的”是固定句式，强调已发生事情的来源或方式，“是老师借给小明的”说明书的来源，通顺。",
       "distractors": [
        "“把老师借给小明的”不通，“把”是处置式，不用在这里。",
        "“跟老师借给小明的”不通，“跟”表示和某人一起，不合这里。",
        "“对老师借给小明的”不通，“对”表示方向或态度，不合这里。",
        "✓ 正确答案：是……的，强调已知事情的来源，是固定句式。"
       ],
       "trapType": "yufa",
       "memoryTip": "固定句式：是＋（来源/方式/时间）＋的。强调怎么来的、谁给的，用”是……的”。"
      },
      "explanation": "“是……的”强调句用来说明已经发生的事情的来源、方式或时间。”是老师借给小明的”说明书是怎么来的。\n另外三个不对：把字句处置某物；跟表示陪伴；对表示方向或态度。三个介词都不能在这里单独撑起句子的意思。\n【语法的方法】问”这东西是哪里来的？谁给的？”答案要用”是……的”来强调。",
      "sentence_en": "This storybook ___ (was) lent to Xiao Ming by the teacher; he must take good care of it.",
      "hints": [
       "The sentence explains where the book came from. Which word starts the fixed pattern 是……的, used to explain the source of something?"
      ],
      "keywords": [
       {
        "w": "是",
        "py": "shì",
        "en": "is; was (emphasis marker)"
       },
       {
        "w": "爱惜",
        "py": "àixī",
        "en": "to treasure; take good care of"
       },
       {
        "w": "故事书",
        "py": "gùshìshū",
        "en": "storybook"
       }
      ],
      "explanation_en": "是……的 is a fixed pattern used to emphasise the source or background of something that already happened. 是老师借给小明的 explains where the book came from. 把, 跟 and 对 do not work here."
     },
     {
      "id": "ZD01_C4",
      "topic": "VocabMcq",
      "sentence": "小鸟______风吹走了，找不到回家的路。",
      "options": [
       "跟",
       "把",
       "被",
       "对"
      ],
      "answer": 2,
      "lesson": 2,
      "skill": "yufa",
      "explain": {
       "why": "“被风吹走了”是被字句，表示小鸟受到”风”的动作影响，是被动句，意思通顺。",
       "distractors": [
        "“跟风吹走了”不通，“跟”表示和某人一起，不用在这里。",
        "“把风吹走了”意思变了，成了小鸟把风吹走，主动和被动搞反了。",
        "✓ 正确答案：被＋施事者（风）＋动词，是被动句，表示主语受到了某人或某物的动作。",
        "“对风吹走了”不通，“对”表示方向或态度，不合这里。"
       ],
       "trapType": "yufa",
       "memoryTip": "被字句公式：主语（受影响的）＋被＋施事者＋动词。小鸟是受影响的，风是施事者，所以”小鸟被风吹走了”。"
      },
      "explanation": "小鸟是被动受影响的，风是做出动作的一方。被字句：主语受影响＋被＋做动作的东西＋动词。\n另外三个不对：跟表示陪伴；把字句要主语主动处置某物，但这里小鸟是被动的；对表示方向或态度。\n【语法的方法】分清主动（用把）和被动（用被）：主语是”做”动作的用把；主语是”被做”动作的用被。",
      "sentence_en": "The little bird ___ (was) blown away by the wind and could not find its way home.",
      "hints": [
       "The bird did not choose to fly away — the wind made it happen. Which word shows that the bird was acted upon by the wind (passive sentence)?"
      ],
      "keywords": [
       {
        "w": "被",
        "py": "bèi",
        "en": "by (passive marker)"
       },
       {
        "w": "吹走",
        "py": "chuīzǒu",
        "en": "blown away"
       },
       {
        "w": "小鸟",
        "py": "xiǎoniǎo",
        "en": "little bird"
       }
      ],
      "explanation_en": "被 is the passive marker. 小鸟被风吹走了 means the bird was blown away by the wind — the bird did not act, it was acted upon. 把 is for active sentences where the subject does something to an object."
     },
     {
      "id": "ZD01_C5",
      "topic": "VocabMcq",
      "sentence": "爸爸______我说，只要努力，什么事都能做好。",
      "options": [
       "被",
       "把",
       "对",
       "跟"
      ],
      "answer": 2,
      "lesson": 1,
      "skill": "yufa",
      "explain": {
       "why": "“对我说”是固定搭配，表示向某人说话，“爸爸对我说”意思通顺、符合中文习惯。",
       "distractors": [
        "“被我说”意思变成了爸爸被我说，主动被动搞反了，不合语境。",
        "“把我说”不通，“说”后面没有结果补语，不能用把字句。",
        "✓ 正确答案：对＋人＋说，是固定搭配，表示向某人说话。",
        "“跟我说”在口语中也常见，但”对我说”是书面固定搭配，更准确。"
       ],
       "trapType": "yufa",
       "memoryTip": "固定搭配：对＋（人）＋说。爸爸把话的方向朝着”我”说，所以用”对”。"
      },
      "explanation": "“对……说”是固定搭配，表示说话的方向是朝着某人的。”爸爸对我说”意思是爸爸把话说给我听。\n另外三个不对：被字句表示被动，不合这里爸爸主动说话的语境；把字句要有结果补语，“说”后面没有；跟我说虽然口语常见，但”对我说”才是书面固定搭配。\n【语法的方法】看到”说”这个动词，前面的对象用”对＋人＋说”来表达。",
      "sentence_en": "Dad said ___ (to) me that as long as you work hard, you can do anything well.",
      "hints": [
       "Dad is speaking in the direction of 'me'. Which preposition means 'to (a person)' and pairs with 说?"
      ],
      "keywords": [
       {
        "w": "对",
        "py": "duì",
        "en": "to; toward"
       },
       {
        "w": "努力",
        "py": "nǔlì",
        "en": "to work hard"
       },
       {
        "w": "说",
        "py": "shuō",
        "en": "to say; to speak"
       }
      ],
      "explanation_en": "对……说 is a fixed pattern meaning 'to say to someone'. 爸爸对我说 means Dad said to me. 被 is passive, 把 needs a result complement, and 跟 is less formal here."
     },
     {
      "id": "ZD01_C6",
      "topic": "VocabMcq",
      "sentence": "小文______书包放在椅子上，然后跑去操场玩。",
      "options": [
       "被",
       "对",
       "跟",
       "把"
      ],
      "answer": 3,
      "lesson": 1,
      "skill": "yufa",
      "explain": {
       "why": "“把书包放在椅子上”是把字句，小文主动对”书包”做出”放”的动作，句式完整。",
       "distractors": [
        "“被书包放在椅子上”不通，书包不会自己做动作，主动被动搞反了。",
        "“对书包放在椅子上”不通，“对”表示方向或态度，不能这样用。",
        "“跟书包放在椅子上”不通，“跟”表示和某人一起，不合这里。",
        "✓ 正确答案：把＋书包＋放在椅子上，是标准把字句，主语主动处置某物。"
       ],
       "trapType": "yufa",
       "memoryTip": "把字句：谁（主语）把（某物）放/拿/送去哪里。小文是主动的人，书包是被放的东西，所以选”把”。"
      },
      "explanation": "小文主动把书包放到椅子上，是把字句：小文（主语）＋把＋书包（受影响的物）＋放在椅子上（动词＋地点）。\n另外三个不对：被字句要主语是被动的；对表示方向；跟表示陪伴。这里小文是主动做动作的人，应该用把。\n【语法的方法】主语主动处置某物并说明结果或去处，就用把字句。",
      "sentence_en": "Xiao Wen ___ (put) her school bag on the chair, then ran to the playground.",
      "hints": [
       "Xiao Wen is actively doing something with her school bag. Which word introduces the object (school bag) in an active disposal sentence?"
      ],
      "keywords": [
       {
        "w": "把",
        "py": "bǎ",
        "en": "disposal marker"
       },
       {
        "w": "书包",
        "py": "shūbāo",
        "en": "school bag"
       },
       {
        "w": "操场",
        "py": "cāochǎng",
        "en": "playground"
       }
      ],
      "explanation_en": "把-sentence: subject + 把 + object + verb + result/location. Xiao Wen actively puts the bag somewhere, so use 把. 被 is passive, 对 shows direction or attitude, 跟 means 'together with'."
     },
     {
      "id": "ZD01_C7",
      "topic": "VocabMcq",
      "sentence": "这幅画______同学们称赞，大家都说画得很好看。",
      "options": [
       "把",
       "跟",
       "对",
       "被"
      ],
      "answer": 3,
      "lesson": 3,
      "skill": "yufa",
      "explain": {
       "why": "“被同学们称赞”是被字句，这幅画是受到称赞的一方，同学们是做出称赞动作的一方，句式通顺。",
       "distractors": [
        "“把同学们称赞”不通，“把”后面要接受处置的物，不是发出动作的人。",
        "“跟同学们称赞”不通，“跟”表示和某人一起，不合这里。",
        "“对同学们称赞”不通，“对”后面要接态度的对象，不合这里。",
        "✓ 正确答案：被＋同学们＋称赞，是被动句，这幅画是受称赞的一方。"
       ],
       "trapType": "yufa",
       "memoryTip": "被字句：主语（受影响的）＋被＋做动作的人＋动词。画是被称赞的，不是主动称赞别人的，所以用”被”。"
      },
      "explanation": "这幅画是被动受到称赞的，同学们是主动发出称赞的一方。被字句：受影响的主语＋被＋做动作的人＋动词。\n另外三个不对：把字句要主语主动处置某物；跟表示陪伴；对表示方向或态度。\n【语法的方法】问”画是主动称赞别人，还是被别人称赞？”——是被别人称赞，所以用”被”。",
      "sentence_en": "This painting ___ (was) praised by the classmates; everyone said it looked very beautiful.",
      "hints": [
       "The painting did not praise anyone — the classmates praised it. Which word shows that the painting was acted upon (passive)?"
      ],
      "keywords": [
       {
        "w": "被",
        "py": "bèi",
        "en": "by (passive marker)"
       },
       {
        "w": "称赞",
        "py": "chēngzàn",
        "en": "to praise"
       },
       {
        "w": "同学",
        "py": "tóngxué",
        "en": "classmate"
       }
      ],
      "explanation_en": "被 marks a passive sentence. 这幅画被同学们称赞 means the painting was praised by the classmates. The painting received the action, it did not do it. Use 被 when the subject is acted upon."
     },
     {
      "id": "ZD01_C8",
      "topic": "VocabMcq",
      "sentence": "奶奶______健康非常关心，每天早上都去公园散步。",
      "options": [
       "跟",
       "把",
       "被",
       "对"
      ],
      "answer": 3,
      "lesson": 1,
      "skill": "yufa",
      "explain": {
       "why": "“对健康非常关心”是固定搭配，“对”表示态度朝着某件事，“对健康关心”意思完整通顺。",
       "distractors": [
        "“跟健康非常关心”不通，“跟”表示和某人一起，不用在这里。",
        "“把健康非常关心”不通，“关心”后面没有明确的处置结果，不能用把字句。",
        "“被健康非常关心”不通，健康不会做动作去关心奶奶，主动被动搞反了。",
        "✓ 正确答案：对＋事情＋关心，是固定搭配，表示对某件事情投入关注。"
       ],
       "trapType": "yufa",
       "memoryTip": "固定搭配：对＋（事情/人）＋关心/重视/感兴趣。看到”关心、重视”这类词，前面常用”对”。"
      },
      "explanation": "“对……关心”是固定搭配，“对”引出关心的对象。”奶奶对健康非常关心”说明奶奶把注意力和关心投向健康这件事。\n另外三个不对：跟表示陪伴；把字句需要明确的处置结果；被字句要主语是被动的，健康不能做动作关心奶奶。\n【语法的方法】遇到”关心、重视、感兴趣、满意”这类词，前面的介词固定用”对”。",
      "sentence_en": "Grandmother is very concerned ___ (about) her health and goes to the park for a walk every morning.",
      "hints": [
       "Grandmother's concern is directed toward her health. Which preposition shows the direction of her attitude or concern?"
      ],
      "keywords": [
       {
        "w": "对",
        "py": "duì",
        "en": "about; toward"
       },
       {
        "w": "关心",
        "py": "guānxīn",
        "en": "to be concerned about"
       },
       {
        "w": "健康",
        "py": "jiànkāng",
        "en": "health"
       }
      ],
      "explanation_en": "对……关心 is a fixed pattern meaning 'to be concerned about something'. 奶奶对健康非常关心 means grandmother is very concerned about health. When you see 关心, 重视 or 感兴趣, the preposition before the topic is almost always 对."
     },
     {
      "id": "ZD01_C9",
      "topic": "VocabMcq",
      "sentence": "弟弟______这道数学题感到很困难，一直在想答案。",
      "options": [
       "对",
       "把",
       "给",
       "跟"
      ],
      "answer": 0,
      "lesson": 1,
      "skill": "yufa",
      "explain": {
       "why": "“对……感到”是固定句式，表示针对某件事有某种感受，“对这道数学题感到很困难”意思通顺。",
       "distractors": [
        "✓ 正确答案：对＋事情＋感到，是固定搭配。",
        "“把这道数学题感到很困难”不通，“把”字句用来处置或支配某样东西，不合这里。",
        "“给这道数学题感到很困难”不通，“给”表示给予，后面接接受的人，不合这里。",
        "“跟这道数学题感到很困难”不通，“跟”表示和谁一起或跟随，不合这里。"
       ],
       "trapType": "yufa",
       "memoryTip": "固定句式：对＋（事情）＋感到＋（感受）。看到”感到”就想前面用”对”。"
      },
      "explanation": "“对……感到”是固定说法：某种感受是朝着某样事情而来的，中间要用”对”。\n其余三个都不对：把后面接承受动作的东西（把书放好）；给后面接接受东西的人（给我一本书）；跟表示和谁一起（跟我走）。汉语里只说”对这道题感到困难”，不说”给这道题感到困难”。\n【语法的方法】遇到”感到、满意、失望”这类感受词，前面固定用介词”对”。",
      "sentence_en": "Little brother feels very troubled ___ (by) this maths question and has been thinking about the answer for a long time.",
      "hints": [
       "This is the fixed pattern 对……感到 (to feel something about something). Which character goes before 这道数学题 to form this pattern?"
      ],
      "keywords": [
       {
        "w": "对",
        "py": "duì",
        "en": "toward; about"
       },
       {
        "w": "困难",
        "py": "kùnnán",
        "en": "difficult"
       },
       {
        "w": "答案",
        "py": "dá'àn",
        "en": "answer"
       }
      ],
      "explanation_en": "对……感到 is a fixed pattern meaning 'to feel something about something', so 对这道数学题感到很困难 (feels very troubled by this maths question) makes sense. Fixed pattern: 对 + a thing + 感到 + a feeling. Seeing 感到, think 对. 把, 给 and 跟 do not fit this pattern."
     },
     {
      "id": "ZD01_C10",
      "topic": "VocabMcq",
      "sentence": "妈妈______我说，好好读书才能实现自己的梦想。",
      "options": [
       "对",
       "把",
       "被",
       "让"
      ],
      "answer": 0,
      "lesson": 1,
      "skill": "yufa",
      "explain": {
       "why": "“对我说”是固定句式，表示朝着某个人说话，“对我说”意思通顺。",
       "distractors": [
        "✓ 正确答案：对＋人＋说，是固定搭配，表示对某人讲话。",
        "“把我说”不通，“把”字句后面要接一个处置动作（把书拿来），不能这样用。",
        "“被我说”不通，“被”表示被动（被老师表扬），主语变成了受动者，不合这里。",
        "“让我说”意思变成叫我来说，主语变了，不合这里妈妈对我说的意思。"
       ],
       "trapType": "yufa",
       "memoryTip": "固定句式：对＋（某人）＋说。有人讲话给另一个人听，就用”对……说”。"
      },
      "explanation": "“对……说”是固定说法：说话的方向是朝着某个人，所以用”对”。\n把后面要有处置动作（把门关上）；被表示被动，主语是受动的人（书被他拿走了）；让表示叫/允许（让我来帮你），主语和意思都不同。\n【语法的方法】句子里有”说”，又要表示”朝着谁说”，固定用”对＋人＋说”。",
      "sentence_en": "Mum said ___ (to) me that studying hard is the way to make your dreams come true.",
      "hints": [
       "Someone is speaking in the direction of another person. Which character forms the fixed pattern 对……说 (to say to someone)?"
      ],
      "keywords": [
       {
        "w": "对",
        "py": "duì",
        "en": "to (someone)"
       },
       {
        "w": "梦想",
        "py": "mèngxiǎng",
        "en": "dream"
       },
       {
        "w": "实现",
        "py": "shíxiàn",
        "en": "to achieve; to come true"
       }
      ],
      "explanation_en": "对……说 is a fixed pattern meaning 'to say to someone', so 对我说 (said to me) makes sense. When someone speaks toward another person, use 对 + person + 说. 把, 被 and 让 all change the meaning or structure and do not fit."
     },
     {
      "id": "ZD01_C11",
      "topic": "VocabMcq",
      "sentence": "他______认真地完成作业，从来不马虎。",
      "options": [
       "总是",
       "虽然",
       "因为",
       "虽然"
      ],
      "answer": 0,
      "lesson": 2,
      "skill": "yufa",
      "explain": {
       "why": "“总是认真地完成作业，从来不马虎”表示一贯的习惯，“总是”表示一直、每次都这样，最符合语境。",
       "distractors": [
        "✓ 正确答案：总是＝一直、每次都这样，表示习惯性的动作。",
        "“虽然认真地完成作业”后面要接”但是……”表示转折，和”从来不马虎”不搭。",
        "“因为认真地完成作业”后面要接”所以……”表示结果，不合这里的句子结构。",
        "“虽然”已在选项二出现，重复选项，必然不对。"
       ],
       "trapType": "yufa",
       "memoryTip": "看句子有没有”但是”或”所以”：有”但是”才选”虽然”，有”所以”才选”因为”；两个都没有，就用”总是”表示习惯。"
      },
      "explanation": "句子说”认真完成作业，从来不马虎”，这是在描述一个人的一贯习惯，没有转折，也没有结果，所以要用表示”一直这样”的”总是”。\n虽然要和”但是”搭配（虽然……但是……）；因为要和”所以”搭配（因为……所以……）。句子里这两个关联词都没有，所以不能选它们。\n【语法的方法】先看句子有没有关联词（但是、所以），再决定用哪个副词；没有关联词就选表示习惯的”总是”。",
      "sentence_en": "He ___ (always) finishes his homework carefully and is never careless.",
      "hints": [
       "The sentence describes a regular habit with no 'but' or 'so' in sight. Which word means 'always' and shows a repeated habit?"
      ],
      "keywords": [
       {
        "w": "总是",
        "py": "zǒngshì",
        "en": "always"
       },
       {
        "w": "认真",
        "py": "rènzhēn",
        "en": "careful; serious"
       },
       {
        "w": "马虎",
        "py": "mǎhu",
        "en": "careless; sloppy"
       }
      ],
      "explanation_en": "The sentence describes a regular habit — finishing homework carefully and never being sloppy. 总是 means 'always' and shows a repeated habit, which fits perfectly. 虽然 needs a 但是 (but) to complete the pattern, and 因为 needs a 所以 (so); neither of those linking words appears here."
     },
     {
      "id": "ZD01_C12",
      "topic": "VocabMcq",
      "sentence": "______天气这么冷，我们还是决定出发去爬山。",
      "options": [
       "虽然",
       "因为",
       "总是",
       "对于"
      ],
      "answer": 0,
      "lesson": 3,
      "skill": "yufa",
      "explain": {
       "why": "“虽然天气这么冷，我们还是决定出发”前后形成转折关系，“虽然……还是……”是固定的转折句式。",
       "distractors": [
        "✓ 正确答案：虽然……还是……，是表示转折的固定搭配。",
        "“因为天气这么冷，我们还是决定出发”不通，“因为”要和”所以”搭配，表示原因和结果，不表示转折。",
        "“总是天气这么冷”不通，“总是”是副词，表示习惯，不能放在这个位置连接两个分句。",
        "“对于天气这么冷”不通，“对于”是介词，表示针对某事，后面不直接接形容词短语来这样使用。"
       ],
       "trapType": "yufa",
       "memoryTip": "看后半句有没有”还是”或”但是”：有”还是”就在前半句选”虽然”，两者固定搭配。"
      },
      "explanation": "后半句有”还是”，这是转折的信号词。”虽然……还是……”是固定的转折句式，表示前面的情况没有改变后面的决定。\n因为要和”所以”搭配表示因果，和”还是”不搭；总是是副词，不能放在句首连接两个分句；对于是介词，用法不同（对于这件事，我有看法）。\n【语法的方法】先找后半句的关键词：看到”还是”或”但是”，前面就填”虽然”。",
      "sentence_en": "___ (Although) the weather is so cold, we still decided to set off and climb the mountain.",
      "hints": [
       "Look at the second half of the sentence — it has 还是 (still). Which word pairs with 还是 to show a contrast or surprise?"
      ],
      "keywords": [
       {
        "w": "虽然",
        "py": "suīrán",
        "en": "although"
       },
       {
        "w": "决定",
        "py": "juédìng",
        "en": "to decide"
       },
       {
        "w": "出发",
        "py": "chūfā",
        "en": "to set off"
       }
      ],
      "explanation_en": "The second half of the sentence has 还是 (still), which is a signal for contrast. 虽然……还是…… is a fixed pattern meaning 'although … still …', so 虽然 fits perfectly at the start. 因为 pairs with 所以 (so) for cause and effect, not contrast. 总是 and 对于 cannot link two clauses this way."
     }
    ]
   }
  ]
 },
 {
  "setId": "ZD02",
  "theme": "drill lianci",
  "track": "HCL",
  "band": "mid",
  "seedSources": [
   "gen:lianci"
  ],
  "plan": [
   {
    "type": "VocabMcq",
    "marks": 14,
    "items": [
     {
      "id": "ZD02_C1",
      "topic": "VocabMcq",
      "sentence": "天空突然下起大雨，______我们已经带了雨伞，所以没有淋湿。",
      "options": [
       "因为",
       "虽然",
       "但是",
       "幸好"
      ],
      "answer": 3,
      "lesson": 2,
      "skill": "lianci",
      "explain": {
       "why": "句子说”下起大雨”但”没有淋湿”，说明有一个幸运的原因，用”幸好”表示庆幸最合适。",
       "distractors": [
        "“因为”引出原因，但句子已有”所以”，两者不能同时出现在句首这个位置引出庆幸语气。",
        "“虽然”要和”但是”搭配，句子里已有”所以”，搭配不当。",
        "“但是”表示转折，和”所以”不能连用，逻辑不通。",
        "✓ 正确答案：幸好＝还好、庆幸的意思，表示避开了坏结果。"
       ],
       "trapType": "lianci",
       "memoryTip": "遇到”还好没出事”的情景，就用”幸好”。记住：幸好＋好结果。"
      },
      "explanation": "句子讲的是下大雨但没有淋湿，表示庆幸，所以用”幸好”。\n”因为……所以”是因果搭配，句子里已有”所以”，不能再在句首加”因为”充当庆幸语气词；”虽然”要和”但是”搭配，不和”所以”搭配；”但是”表转折，不能和”所以”连用。\n【连词方法】先看句子表达的是庆幸、转折还是因果，再选对应的连词。",
      "explanation_en": "The sentence says it rained heavily but no one got wet — this expresses relief. 幸好 means 'luckily / fortunately' and fits this feeling. 因为 pairs with 所以 for cause-effect; 虽然 pairs with 但是 for contrast — neither matches here.",
      "sentence_en": "___ (Luckily) we had already brought umbrellas, so we did not get wet.",
      "hints": [
       "The sentence shows that something bad almost happened but did not — which connective shows you feel relieved and grateful?"
      ],
      "keywords": [
       {
        "w": "幸好",
        "py": "xìnghǎo",
        "en": "luckily; fortunately"
       },
       {
        "w": "雨伞",
        "py": "yǔsǎn",
        "en": "umbrella"
       },
       {
        "w": "淋湿",
        "py": "línshī",
        "en": "to get soaked"
       }
      ]
     },
     {
      "id": "ZD02_C2",
      "topic": "VocabMcq",
      "sentence": "弟弟______很小，______已经会自己穿衣服了。",
      "options": [
       "因为……所以……",
       "虽然……但是……",
       "如果……就……",
       "一边……一边……"
      ],
      "answer": 1,
      "lesson": 1,
      "skill": "lianci",
      "explain": {
       "why": "句子前半说弟弟”很小”，后半说他”会自己穿衣服”，两个意思相反，是转折关系，用”虽然……但是……”最合适。",
       "distractors": [
        "“因为……所以……”表示因果，但”很小”不是”会穿衣服”的原因，逻辑不通。",
        "✓ 正确答案：虽然……但是……表示转折，前后意思相反。",
        "“如果……就……”表示假设，但句子说的是已经发生的事，不是假设。",
        "“一边……一边……”表示同时做两件事，和句子意思完全不符。"
       ],
       "trapType": "lianci",
       "memoryTip": "两件事意思相反？用”虽然……但是……”。记住：虽然＝尽管，但是＝可是。"
      },
      "explanation": "弟弟年纪小，却已经会自己穿衣服，两件事之间有转折关系，所以选”虽然……但是……”。\n”因为……所以……”是因果，“如果……就……”是假设，“一边……一边……”是同时进行，都和这里的转折意思不符。\n【连词配对方法】先判断两个分句的关系：相反→转折（虽然但是）；原因结果→因果（因为所以）；假设→（如果就）；同时→（一边一边）。",
      "explanation_en": "The first part says the brother is very young; the second says he can already dress himself. These two ideas are opposite, so we use 虽然……但是…… (although … but …) to show contrast.",
      "sentence_en": "___ (Although) the younger brother is very young, ___ (he) can already dress himself.",
      "hints": [
       "The two halves of the sentence say opposite things — one unexpected fact follows another. Which pair of connectives shows contrast?"
      ],
      "keywords": [
       {
        "w": "虽然",
        "py": "suīrán",
        "en": "although"
       },
       {
        "w": "但是",
        "py": "dànshì",
        "en": "but; however"
       },
       {
        "w": "穿衣服",
        "py": "chuān yīfu",
        "en": "to put on clothes"
       }
      ]
     },
     {
      "id": "ZD02_C3",
      "topic": "VocabMcq",
      "sentence": "______你认真复习，______能在考试中取得好成绩。",
      "options": [
       "虽然……但是……",
       "一边……一边……",
       "如果……就……",
       "因为……所以……"
      ],
      "answer": 2,
      "lesson": 3,
      "skill": "lianci",
      "explain": {
       "why": "句子讲的是”认真复习”这个条件带来”取得好成绩”的结果，是假设条件关系，用”如果……就……”最合适。",
       "distractors": [
        "“虽然……但是……”表转折，前后意思应该相反，但这里前后是条件和结果，不是转折。",
        "“一边……一边……”表示同时做两件事，和条件结果的逻辑不符。",
        "✓ 正确答案：如果……就……表示假设条件：做到某件事，就会有某个结果。",
        "“因为……所以……”表因果，但这里是假设还没发生的事，不是已知的原因。"
       ],
       "trapType": "lianci",
       "memoryTip": "看到”条件→结果”的句子，就用”如果……就……”。如果＝假设，就＝那么。"
      },
      "explanation": "句子表达的是：只要满足”认真复习”这个条件，就会得到”好成绩”这个结果。这是假设条件关系，用”如果……就……”。\n”虽然……但是……”是转折；”一边……一边……”是同时进行；”因为……所以……”是已知的因果，而这里说的是还没发生的假设情况，所以都不合适。\n【记忆方法】如果＝假设一个条件，就＝条件满足后的结果。",
      "explanation_en": "The sentence gives a condition (study carefully) and its result (get good marks). 如果……就…… (if … then …) is used for this kind of conditional relationship.",
      "sentence_en": "___ (If) you study carefully, you ___ (will) do well in the exam.",
      "hints": [
       "One part gives a condition and the other gives the result. Which connective pair means 'if … then …'?"
      ],
      "keywords": [
       {
        "w": "如果",
        "py": "rúguǒ",
        "en": "if"
       },
       {
        "w": "复习",
        "py": "fùxí",
        "en": "to revise; to review"
       },
       {
        "w": "成绩",
        "py": "chéngjì",
        "en": "results; marks"
       }
      ]
     },
     {
      "id": "ZD02_C4",
      "topic": "VocabMcq",
      "sentence": "姐姐______听音乐______做作业，妈妈叫她专心一点。",
      "options": [
       "因为……所以……",
       "虽然……但是……",
       "如果……就……",
       "一边……一边……"
      ],
      "answer": 3,
      "lesson": 2,
      "skill": "lianci",
      "explain": {
       "why": "姐姐同时在做两件事：听音乐和做作业，表示同时进行，用”一边……一边……”最合适。",
       "distractors": [
        "“因为……所以……”表因果，听音乐不是做作业的原因，逻辑不通。",
        "“虽然……但是……”表转折，两件事不是相反的意思。",
        "“如果……就……”表假设，但这里说的是已经正在发生的事。",
        "✓ 正确答案：一边……一边……表示同时做两件事。"
       ],
       "trapType": "lianci",
       "memoryTip": "两件事同时发生？就用”一边……一边……”。一边A，一边B＝同时做A和B。"
      },
      "explanation": "姐姐同时在听音乐和做作业，两个动作同时进行，所以用”一边……一边……”。\n”因为……所以……”是因果；”虽然……但是……”是转折；”如果……就……”是假设。这三个都不表示同时进行，所以都不对。\n【记忆方法】看到两个动作同时发生，就选”一边……一边……”。",
      "explanation_en": "The sister is doing two things at the same time — listening to music and doing homework. 一边……一边…… (while doing A, also doing B) expresses simultaneous actions.",
      "sentence_en": "The elder sister listens to music ___ while ___ doing her homework, so mum told her to focus.",
      "hints": [
       "Two actions are happening at the same time. Which connective pair means 'while doing one thing, also doing another'?"
      ],
      "keywords": [
       {
        "w": "一边",
        "py": "yībiān",
        "en": "while (doing something)"
       },
       {
        "w": "专心",
        "py": "zhuānxīn",
        "en": "to concentrate; to focus"
       },
       {
        "w": "做作业",
        "py": "zuò zuòyè",
        "en": "to do homework"
       }
      ]
     },
     {
      "id": "ZD02_C5",
      "topic": "VocabMcq",
      "sentence": "小明______生病了，______坚持来学校参加比赛。",
      "options": [
       "一边……一边……",
       "如果……就……",
       "虽然……但是……",
       "因为……所以……"
      ],
      "answer": 2,
      "lesson": 1,
      "skill": "lianci",
      "explain": {
       "why": "“生病”和”坚持来学校”是两个相反的情况，前面是不利条件，后面是出乎意料的行动，是转折关系。",
       "distractors": [
        "“一边……一边……”表示同时进行两件事，和转折意思不符。",
        "“如果……就……”表假设条件，但小明生病是已经发生的事，不是假设。",
        "✓ 正确答案：虽然……但是……前半说不好的情况，后半说出乎意料的结果，是转折。",
        "“因为……所以……”表因果，但生病不是坚持来学校的原因，逻辑不通。"
       ],
       "trapType": "lianci",
       "memoryTip": "前面是坏情况，后面却做了好事或出乎意料的事？就用”虽然……但是……”。"
      },
      "explanation": "小明生病是不好的情况，但他仍然坚持来参加比赛，前后意思相反，所以用”虽然……但是……”表示转折。\n”一边……一边……”是同时；”如果……就……”是假设；”因为……所以……”是因果。三个都和转折无关。\n【方法】虽然前面说的是困难或坏情况，但是后面偏偏发生了出乎意料的好事或行动，就是转折。",
      "explanation_en": "Xiao Ming is sick (bad situation) but still comes to school for the competition (unexpected positive action). These two ideas contrast, so 虽然……但是…… (although … but …) is correct.",
      "sentence_en": "___ (Although) Xiao Ming was sick, ___ (he) still insisted on coming to school for the competition.",
      "hints": [
       "The first half describes a difficult situation, and the second half shows an unexpected action despite that difficulty. Which connective pair expresses this contrast?"
      ],
      "keywords": [
       {
        "w": "虽然",
        "py": "suīrán",
        "en": "although"
       },
       {
        "w": "坚持",
        "py": "jiānchí",
        "en": "to persist; to insist"
       },
       {
        "w": "生病",
        "py": "shēngbìng",
        "en": "to be sick"
       }
      ]
     },
     {
      "id": "ZD02_C6",
      "topic": "VocabMcq",
      "sentence": "______天气太热，______大家都不想出去玩。",
      "options": [
       "虽然……但是……",
       "一边……一边……",
       "如果……就……",
       "因为……所以……"
      ],
      "answer": 3,
      "lesson": 3,
      "skill": "lianci",
      "explain": {
       "why": "“天气太热”是原因，“大家不想出去玩”是结果，是因果关系，用”因为……所以……”最合适。",
       "distractors": [
        "“虽然……但是……”表转折，前后应该意思相反，但这里是原因和结果的关系。",
        "“一边……一边……”表示同时进行，和因果逻辑完全不同。",
        "“如果……就……”表假设，但天气热是已经发生的事实，不是假设。",
        "✓ 正确答案：因为……所以……前面是原因，后面是结果。"
       ],
       "trapType": "lianci",
       "memoryTip": "为什么会这样？因为……；结果怎样？所以……。记住：因为＝原因，所以＝结果。"
      },
      "explanation": "句子里”天气太热”是导致”大家不想出去玩”的原因，前后是因果关系，选”因为……所以……”。\n”虽然……但是……”是转折；”一边……一边……”是同时；”如果……就……”是假设。三个都不表示因果。\n【方法】先问”为什么？”，能回答的就是”因为”；再问”然后怎样？”，能回答的就是”所以”。",
      "explanation_en": "The hot weather is the reason (因为), and not wanting to go out is the result (所以). 因为……所以…… (because … therefore …) links a cause to its effect.",
      "sentence_en": "___ (Because) the weather was too hot, ___ (everyone) did not want to go out to play.",
      "hints": [
       "One part gives a reason and the other gives what happened as a result. Which connective pair means 'because … therefore …'?"
      ],
      "keywords": [
       {
        "w": "因为",
        "py": "yīnwèi",
        "en": "because"
       },
       {
        "w": "所以",
        "py": "suǒyǐ",
        "en": "therefore; so"
       },
       {
        "w": "天气",
        "py": "tiānqì",
        "en": "weather"
       }
      ]
     },
     {
      "id": "ZD02_C7",
      "topic": "VocabMcq",
      "sentence": "爸爸______看报纸______喝茶，享受着周末的早晨。",
      "options": [
       "因为……所以……",
       "一边……一边……",
       "虽然……但是……",
       "如果……就……"
      ],
      "answer": 1,
      "lesson": 2,
      "skill": "lianci",
      "explain": {
       "why": "爸爸同时在做两件事：看报纸和喝茶，两个动作同时进行，用”一边……一边……”最合适。",
       "distractors": [
        "“因为……所以……”表因果，看报纸不是喝茶的原因，逻辑不通。",
        "✓ 正确答案：一边……一边……表示同时做两件事。",
        "“虽然……但是……”表转折，看报纸和喝茶不是相反的事情。",
        "“如果……就……”表假设，但这里说的是正在发生的事。"
       ],
       "trapType": "lianci",
       "memoryTip": "两个动作同时进行？用”一边……一边……”。一边A，一边B＝A和B同时做。"
      },
      "explanation": "爸爸同时在看报纸和喝茶，两个动作同时发生，所以用”一边……一边……”。\n”因为……所以……”是因果；”虽然……但是……”是转折；”如果……就……”是假设。这三个都不能表示两个动作同时进行。\n【方法】找句子里有没有两个同时发生的动作，有的话就用”一边……一边……”。",
      "explanation_en": "Father is doing two things at the same time — reading the newspaper and drinking tea. 一边……一边…… (while doing A, also doing B) is used when two actions happen simultaneously.",
      "sentence_en": "Father reads the newspaper ___ while ___ drinking tea, enjoying the weekend morning.",
      "hints": [
       "Two actions are happening at the same time. Which connective pair expresses doing two things simultaneously?"
      ],
      "keywords": [
       {
        "w": "一边",
        "py": "yībiān",
        "en": "while (doing something)"
       },
       {
        "w": "报纸",
        "py": "bàozhǐ",
        "en": "newspaper"
       },
       {
        "w": "享受",
        "py": "xiǎngshòu",
        "en": "to enjoy"
       }
      ]
     },
     {
      "id": "ZD02_C8",
      "topic": "VocabMcq",
      "sentence": "______你现在不好好保护眼睛，长大后______会后悔。",
      "options": [
       "因为……所以……",
       "虽然……但是……",
       "一边……一边……",
       "如果……就……"
      ],
      "answer": 3,
      "lesson": 4,
      "skill": "lianci",
      "explain": {
       "why": "句子讲的是”不保护眼睛”这个假设条件，带来”会后悔”这个将来的结果，是假设条件关系，用”如果……就……”。",
       "distractors": [
        "“因为……所以……”表因果，但这里说的是还没发生的将来的事，是假设，不是已知原因。",
        "“虽然……但是……”表转折，前后应该意思相反，但这里是条件和结果。",
        "“一边……一边……”表示同时进行，和假设条件完全不符。",
        "✓ 正确答案：如果……就……表示：假设某个条件成立，就会有某个结果。"
       ],
       "trapType": "lianci",
       "memoryTip": "句子在说”假设将来会怎样”？就用”如果……就……”。如果＝假设，就＝那么结果是。"
      },
      "explanation": "句子是在提醒：假设你现在不好好保护眼睛，将来就会后悔。这是一个假设条件和其结果，用”如果……就……”。\n”因为……所以……”是已经发生的因果；”虽然……但是……”是转折；”一边……一边……”是同时进行。三个都不表示假设将来的情况。\n【方法】如果说的是”假设做某事，将来会有某结果”，就选”如果……就……”。",
      "explanation_en": "The sentence warns about a future consequence: if you do not protect your eyes now, you will regret it later. This is a conditional relationship, so 如果……就…… (if … then …) is correct.",
      "sentence_en": "___ (If) you do not take care of your eyes now, you ___ (will) regret it when you grow up.",
      "hints": [
       "The sentence talks about something that has not happened yet — a possible future situation and its consequence. Which connective pair means 'if … then …'?"
      ],
      "keywords": [
       {
        "w": "如果",
        "py": "rúguǒ",
        "en": "if"
       },
       {
        "w": "保护",
        "py": "bǎohù",
        "en": "to protect"
       },
       {
        "w": "后悔",
        "py": "hòuhuǐ",
        "en": "to regret"
       }
      ]
     },
     {
      "id": "ZD02_C9",
      "topic": "VocabMcq",
      "sentence": "天空乌云密布，______要下大雨了，我们快回家吧。",
      "options": [
       "因为",
       "虽然",
       "看来",
       "不管"
      ],
      "answer": 2,
      "lesson": 1,
      "skill": "lianci",
      "explain": {
       "why": "乌云密布是看到的现象，说话人根据这个现象推断”要下大雨了”，用”看来”表示根据眼前情况作出判断，最符合语境。",
       "distractors": [
        "“因为”引出原因，后面要跟”所以”，句子结构不符。",
        "“虽然”表示转折，和后面”要下大雨了”没有转折关系。",
        "✓ 正确答案：看来＝根据眼前情况作出判断。",
        "“不管”表示无论什么条件，后面要跟”都”，句子结构不符。"
       ],
       "trapType": "lianci",
       "memoryTip": "看到现象→作出推断，用”看来”。乌云密布→看来要下雨了。"
      },
      "explanation": "说话人看到”乌云密布”这个现象，推断”要下大雨了”。”看来”表示根据眼前情况作出判断，最合适。\n”因为”引出原因，需要配合”所以”；”虽然”表示转折，需要配合”但是”；”不管”表示无论条件如何，需要配合”都”。这三个连词放在这里，句子结构都说不通。\n【找连词的方法】先弄清楚两件事的关系：是推断、转折、原因还是条件，再选对应的连词。",
      "explanation_en": "The speaker sees dark clouds and concludes it is going to rain. 看来 means 'it seems / it looks like', used when you make a judgement based on what you observe. The other three connectives need different partner words and do not fit the sentence structure here.",
      "sentence_en": "The sky is covered with dark clouds. ___ (It looks like) it is going to rain heavily. Let us hurry home.",
      "hints": [
       "The speaker is making a guess based on what they can see. Which word means 'it seems' or 'it looks like'?"
      ],
      "keywords": [
       {
        "w": "看来",
        "py": "kànlái",
        "en": "it seems; it looks like"
       },
       {
        "w": "乌云",
        "py": "wūyún",
        "en": "dark clouds"
       },
       {
        "w": "密布",
        "py": "mìbù",
        "en": "to cover thickly"
       }
      ]
     },
     {
      "id": "ZD02_C10",
      "topic": "VocabMcq",
      "sentence": "弟弟______年纪小，______懂得关心家人。",
      "options": [
       "因为……所以……",
       "虽然……但是……",
       "只要……就……",
       "不管……都……"
      ],
      "answer": 1,
      "lesson": 2,
      "skill": "lianci",
      "explain": {
       "why": "前半句”年纪小”和后半句”懂得关心家人”形成转折关系，虽然年纪小，却懂事，用”虽然……但是……”最合适。",
       "distractors": [
        "“因为……所以……”表示原因和结果，年纪小不是懂事的原因，不符合。",
        "✓ 正确答案：虽然……但是……表示转折，前后两件事形成对比。",
        "“只要……就……”表示条件，这里没有条件关系。",
        "“不管……都……”表示无论什么情况，这里没有这种意思。"
       ],
       "trapType": "lianci",
       "memoryTip": "年纪小却懂事→出乎意料的转折→用”虽然……但是……”。"
      },
      "explanation": "句子的意思是：年纪小是一件事，懂得关心家人是另一件出乎意料的事，两件事形成转折，用”虽然……但是……”。\n”因为……所以……”表示因果，年纪小不是懂事的原因；”只要……就……”表示条件，这里没有条件关系；”不管……都……”表示无论如何，也不符合这里的意思。\n【转折的标志】前后两件事让人觉得意外、相反，就用”虽然……但是……”。",
      "explanation_en": "The two parts of the sentence contrast each other: being young vs. knowing how to care for family. This is a contrast/concession, so 虽然……但是…… ('although … but …') fits best. The other pairs show cause-effect, condition, or 'no matter what', none of which match.",
      "sentence_en": "Although little brother is young, he still knows how to care for the family.",
      "hints": [
       "The two halves of the sentence are surprising opposites — being young but still being thoughtful. Which pair of connectives shows this kind of contrast?"
      ],
      "keywords": [
       {
        "w": "虽然",
        "py": "suīrán",
        "en": "although"
       },
       {
        "w": "但是",
        "py": "dànshì",
        "en": "but; however"
       },
       {
        "w": "年纪",
        "py": "niánjì",
        "en": "age"
       }
      ]
     },
     {
      "id": "ZD02_C11",
      "topic": "VocabMcq",
      "sentence": "______你每天坚持练习，______能写出一手好字。",
      "options": [
       "虽然……但是……",
       "因为……所以……",
       "只要……就……",
       "不管……都……"
      ],
      "answer": 2,
      "lesson": 3,
      "skill": "lianci",
      "explain": {
       "why": "前半句”每天坚持练习”是条件，后半句”能写出一手好字”是满足条件后的结果，用”只要……就……”表示条件关系最合适。",
       "distractors": [
        "“虽然……但是……”表示转折，这里没有转折关系。",
        "“因为……所以……”表示原因和结果，强调已发生的因果，而这里强调的是将来的条件。",
        "✓ 正确答案：只要……就……表示满足某个条件，结果就会出现。",
        "“不管……都……”表示无论什么情况结果都一样，和”坚持练习”的条件意思不同。"
       ],
       "trapType": "lianci",
       "memoryTip": "条件→结果，用”只要……就……”。只要做到A，就能得到B。"
      },
      "explanation": "句子的意思是：满足”每天坚持练习”这个条件，就能得到”写出好字”的结果。”只要……就……”专门表示这种条件关系。\n”虽然……但是……”是转折，这里没有转折；”因为……所以……”是已经发生的因果，这里是将来的条件；”不管……都……”是说无论什么条件结果都不变，和这里”坚持才能成功”的意思相反。\n【条件关系的标志】满足A，才能得到B，就用”只要A，就B”。",
      "explanation_en": "The sentence means: if you meet the condition of practising every day, you will get the result of writing well. 只要……就…… ('as long as … then …') expresses this condition-result relationship. The other pairs show contrast, past cause-effect, or 'regardless of condition'.",
      "sentence_en": "As long as you practise every day, you will be able to write beautifully.",
      "hints": [
       "The first half gives a condition, and the second half gives the result of meeting that condition. Which pair of connectives means 'as long as … then …'?"
      ],
      "keywords": [
       {
        "w": "只要",
        "py": "zhǐyào",
        "en": "as long as"
       },
       {
        "w": "坚持",
        "py": "jiānchí",
        "en": "to keep up; to persist"
       },
       {
        "w": "练习",
        "py": "liànxí",
        "en": "to practise"
       }
      ]
     },
     {
      "id": "ZD02_C12",
      "topic": "VocabMcq",
      "sentence": "______风吹得多大，爷爷______坚持出去晨练。",
      "options": [
       "只要……就……",
       "虽然……但是……",
       "因为……所以……",
       "不管……都……"
      ],
      "answer": 3,
      "lesson": 4,
      "skill": "lianci",
      "explain": {
       "why": "前半句”风吹得多大”表示任何情况，后半句”坚持出去晨练”表示结果不变，用”不管……都……”最合适。",
       "distractors": [
        "“只要……就……”表示满足某个条件才有结果，而这里强调无论什么情况结果都一样。",
        "“虽然……但是……”表示转折，句子结构和意思不符。",
        "“因为……所以……”表示因果，这里不是在说原因和结果。",
        "✓ 正确答案：不管……都……表示无论什么情况，结果都不变。"
       ],
       "trapType": "lianci",
       "memoryTip": "无论什么情况，结果都一样→用”不管……都……”。"
      },
      "explanation": "句子的意思是：无论风有多大，爷爷晨练的行动都不会改变。”不管……都……”专门表示这种”无论什么情况，结果都不变”的关系。\n”只要……就……”是满足条件才有结果，这里爷爷不是”满足某个条件才去晨练”，而是无论什么情况都去；”虽然……但是……”是转折，句子结构不符；”因为……所以……”是因果，这里没有因果关系。\n【不管……都的标志】前面可以填”多大、多远、多难”等程度词，后面结果不变。",
      "explanation_en": "The sentence means: no matter how strong the wind is, grandfather still goes out to exercise. 不管……都…… ('no matter … still …') expresses that the result stays the same regardless of the situation. The other pairs show condition, contrast, or cause-effect.",
      "sentence_en": "No matter how strong the wind is, grandfather still insists on going out for his morning exercise.",
      "hints": [
       "Grandfather exercises every day no matter what the weather is like. Which connective pair means 'no matter what … still …'?"
      ],
      "keywords": [
       {
        "w": "不管",
        "py": "bùguǎn",
        "en": "no matter; regardless"
       },
       {
        "w": "坚持",
        "py": "jiānchí",
        "en": "to insist; to keep up"
       },
       {
        "w": "晨练",
        "py": "chénliàn",
        "en": "morning exercise"
       }
      ]
     },
     {
      "id": "ZD02_C13",
      "topic": "VocabMcq",
      "sentence": "小明忘记带雨伞，______天突然下起雨来，他的衣服全湿了。",
      "options": [
       "所以",
       "虽然",
       "只要",
       "不管"
      ],
      "answer": 0,
      "lesson": 1,
      "skill": "lianci",
      "explain": {
       "why": "前半句”忘记带雨伞”是原因，后半句”衣服全湿了”是结果，用”所以”连接因果关系最合适。",
       "distractors": [
        "✓ 正确答案：所以＝表示结果，前面的原因导致了这个结果。",
        "“虽然”表示转折，需要配合”但是”，句子结构不符。",
        "“只要”表示条件，需要配合”就”，句子结构不符。",
        "“不管”表示无论什么情况，需要配合”都”，句子结构不符。"
       ],
       "trapType": "lianci",
       "memoryTip": "忘带伞→淋湿了，是因果关系，用”所以”表示结果。"
      },
      "explanation": "句子前半部分说了两个原因：忘记带雨伞，天又突然下雨，后半部分是这两个原因造成的结果——衣服全湿了。”所以”连接原因和结果，放在结果前面，最合适。\n”虽然”需要配合”但是”一起用；”只要”需要配合”就”一起用；”不管”需要配合”都”一起用。这三个连词单独放在这里，句子都说不通。\n【单个连词的方法】看空格前后有没有搭档连词，没有的话就选可以单独使用的”所以”。",
      "explanation_en": "The first part gives two reasons (forgot umbrella + sudden rain) and the second part gives the result (clothes all wet). 所以 ('so; therefore') connects a cause to its result and can be used alone here. The other three connectives each need a partner word and do not fit on their own.",
      "sentence_en": "Xiao Ming forgot to bring his umbrella, and it suddenly started to rain, so his clothes got completely wet.",
      "hints": [
       "The first part tells us what went wrong. The second part tells us what happened as a result. Which word means 'so' or 'therefore' and introduces a result?"
      ],
      "keywords": [
       {
        "w": "所以",
        "py": "suǒyǐ",
        "en": "so; therefore"
       },
       {
        "w": "忘记",
        "py": "wàngjì",
        "en": "to forget"
       },
       {
        "w": "突然",
        "py": "tūrán",
        "en": "suddenly"
       }
      ]
     },
     {
      "id": "ZD02_C14",
      "topic": "VocabMcq",
      "sentence": "姐姐______生病了，______还是坚持去学校参加考试。",
      "options": [
       "不管……都……",
       "只要……就……",
       "虽然……但是……",
       "因为……所以……"
      ],
      "answer": 2,
      "lesson": 2,
      "skill": "lianci",
      "explain": {
       "why": "前半句”生病了”和后半句”坚持去学校”是出乎意料的对比，生病了本来应该休息，但她还是去考试，形成转折，用”虽然……但是……”最合适。",
       "distractors": [
        "“不管……都……”表示无论什么情况，但这里强调的是生病这一具体情况下的转折，不是泛指任何情况。",
        "“只要……就……”表示条件，生病不是去考试的条件，不符合。",
        "✓ 正确答案：虽然……但是……表示转折，前后两件事让人意外。",
        "“因为……所以……”表示因果，生病不是去考试的原因，不符合。"
       ],
       "trapType": "lianci",
       "memoryTip": "生病了→出人意料还是去考试→转折→用”虽然……但是……”。"
      },
      "explanation": "生病了，一般人会留在家里休息，但姐姐却坚持去考试，这是让人意外的转折，所以用”虽然……但是……”。\n”不管……都……”泛指任何情况，这里说的是”生病”这一具体情况，用”不管”语气太强；”只要……就……”是满足条件才有结果，这里生病不是条件；”因为……所以……”是因果，生病不是去考试的原因。\n【虽然和不管的区别】具体说某一件事形成对比→虽然；泛指任何情况结果都不变→不管。",
      "explanation_en": "Sister is sick but still goes to school for the exam — this is a surprising contrast. 虽然……但是…… ('although … but …') shows this contrast. 不管……都…… refers to any situation in general, while here we are talking about one specific situation (being sick).",
      "sentence_en": "Although sister was sick, she still insisted on going to school to take the exam.",
      "hints": [
       "Being sick and still going to take an exam is a surprising contrast. Which pair of connectives means 'although … but …' and shows two opposite ideas?"
      ],
      "keywords": [
       {
        "w": "虽然",
        "py": "suīrán",
        "en": "although"
       },
       {
        "w": "但是",
        "py": "dànshì",
        "en": "but; however"
       },
       {
        "w": "坚持",
        "py": "jiānchí",
        "en": "to insist; to persist"
       }
      ]
     }
    ]
   }
  ]
 }
]
/* WA1_ZH_DRILL_JSON_END */
;

export default WA1_ZH_DRILL;
