/* ============================================================
   build_wa1_practice.js  (step 3-3)
   60-set practice JSON (+8-type comp) -> src/data/p3/english/wa1_practice.ts
   convertSet() is the SAME logic validated by verify_mapping.js.
   After writing, the file is re-read from disk, parsed back, and the full
   round-trip/invariant check is re-run on the on-disk data (catches any
   serialization error -- not just in-memory correctness).
   ============================================================ */
const fs = require('fs');
const path = require('path');

const WA1_FILE  = '20260622_WA1_complete.json';
const COMP_FILE = 'comp60_FINAL_8type_backup.json';
const OUT       = path.join('src', 'data', 'p3', 'english', 'wa1_practice.ts');

const WA1  = JSON.parse(fs.readFileSync(WA1_FILE, 'utf8'));
const COMP = JSON.parse(fs.readFileSync(COMP_FILE, 'utf8'));
const setsById = Object.fromEntries(WA1.sets.map(s => [s.set_id, s]));
const SECTION_ORDER = ['GrammarMCQ', 'VocabMCQ', 'GrammarCloze', 'VocabCloze', 'Editing', 'Synthesis', 'Comprehension'];

/* ---------- converter helpers (identical to verify_mapping) ---------- */
function wordBankArray(wb) { return Array.isArray(wb) ? wb.slice() : Object.values(wb || {}); }
function normWord(answer, wb) {
  if (typeof answer === 'string' && wb && !Array.isArray(wb)
      && Object.prototype.hasOwnProperty.call(wb, answer.trim())) return wb[answer.trim()];
  return answer;
}
function sentenceContaining(passage, word) {
  if (!word) return '';
  const parts = String(passage).split(/(?<=[.!?])\s+/);
  return parts.find(p => p.includes(word)) || '';
}

/* ---------- per-set converter -> { type -> PlanSection } ---------- */
function convertSet(setId) {
  const raw = setsById[setId], S = raw.sections, out = {};
  for (const [key, type] of [['A', 'VocabMCQ'], ['B', 'GrammarMCQ']]) {
    const sec = S[key];
    const items = sec.questions.map((q, i) => ({
      id: `${setId}_${key}_${q.question_id ?? i}`,
      topic: type,
      sentence: q.stem,
      options: Object.values(q.options),
      answer: parseInt(q.answer, 10) - 1,
      explanation: q.learning_tip,
    }));
    out[type] = { type, items, marks: items.length };
  }
  for (const [key, type] of [['C', 'GrammarCloze'], ['D', 'VocabCloze']]) {
    const sec = S[key];
    const set = {
      id: `${setId}_${key}`,
      passage: sec.passage,
      wordBank: wordBankArray(sec.word_box),
      blanks: sec.questions.map(q => ({ num: q.blank_number, answer: normWord(q.answer, sec.word_box), hint: q.trap_type, explanation: q.learning_tip })),
    };
    out[type] = { type, items: [set], marks: set.blanks.length };
  }
  {
    const sec = S.E, cont = sec.errors || sec.questions || [];
    const items = cont.map(it => {
      const wrong = it.wrong_word || it.error_word;
      return {
        id: `${setId}_E_${it.question_id ?? it.blank_number}`,
        answer: it.correction,
        questionNumber: it.blank_number,
        wrongWord: wrong,
        sentence: sentenceContaining(sec.passage, wrong),
      };
    });
    out.Editing = { type: 'Editing', items: [{ id: `${setId}_E`, items }], marks: items.length };
  }
  {
    const sec = S.F || S.f, fqs = (sec && sec.questions) || [];
    const items = fqs.map((q, i) => ({
      id: `${setId}_F${i + 1}`,
      sentenceA: q.sentence1 != null ? q.sentence1 : q.sentence_a,
      sentenceB: (q.sentence2 != null ? q.sentence2 : q.sentence_b) || undefined,
      starter: q.starter || undefined,
      instruction: q.instruction,
      answer: q.model_answer,
      answerSimple: q.model_answer_simple || undefined,
      hint: q.trap_type,
      explanation: q.learning_tip,
      marks: q.marks || 2,
    }));
    out.Synthesis = { type: 'Synthesis', items, marks: items.reduce((a, q) => a + (q.marks || 0), 0) };
  }
  {
    const c = COMP[setId], qs = c.generated.questions;
    const marks = qs.reduce((a, q) => a + (q.marks || 1), 0);
    out.Comprehension = { type: 'Comprehension', items: [{ id: `${setId}_G`, passage: c.passage, questions: qs }], marks };
  }
  return out;
}

/* ---------- build PracticeSet[] (plan ordered by SECTION_ORDER) ---------- */
const practiceSets = WA1.sets.map(raw => {
  const byType = convertSet(raw.set_id);
  return { setId: raw.set_id, theme: raw.theme, plan: SECTION_ORDER.map(t => byType[t]) };
});

/* ---------- emit .ts ---------- */
const HEADER = `// AUTO-GENERATED by build_wa1_practice.js -- DO NOT EDIT BY HAND.
// Source: ${WA1_FILE} (+ ${COMP_FILE}). Regenerate to update.
// Shapes match the fields ExamSession.js renderers actually read.

export type SectionType =
  | 'GrammarMCQ' | 'VocabMCQ' | 'GrammarCloze' | 'VocabCloze' | 'Editing' | 'Synthesis' | 'Comprehension';

export interface McqItem { id: string; topic: SectionType; sentence: string; options: string[]; answer: number; explanation?: string; }
export interface ClozeBlank { num: number; answer: string; hint?: string; explanation?: string; }
export interface ClozeSet { id: string; passage: string; wordBank: string[]; blanks: ClozeBlank[]; }
export interface EditItem { id: string; answer: string; questionNumber: number; wrongWord: string; sentence: string; }
export interface EditSet { id: string; items: EditItem[]; }
export interface CompQuestion {
  id: string; questionNo?: string | number; format: string; marks?: number; stem: string;
  answer: any; acceptableAnswers?: string[]; options?: string[]; abSentence?: string;
  abChoices?: Record<string, string>; statements?: string[]; sequenceItems?: string[];
  solution?: Record<string, any>;
}
export interface CompSet { id: string; passage: string; questions: CompQuestion[]; }
export interface SynthItem { id: string; sentenceA: string; sentenceB?: string; starter?: string; instruction: string; answer: string; answerSimple?: string; hint?: string; explanation?: string; marks: number; }
export interface PlanSection { type: SectionType; items: Array<McqItem | ClozeSet | EditSet | CompSet | SynthItem>; marks: number; }
export interface PracticeSet { setId: string; theme: string; plan: PlanSection[]; }

export const WA1_PRACTICE_SETS: PracticeSet[] = `;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, HEADER + JSON.stringify(practiceSets, null, 2) + ';\n', 'utf8');
console.log('Wrote', OUT, '(' + practiceSets.length + ' sets, ' + (fs.statSync(OUT).size / 1024 | 0) + ' KB)');

/* ============================================================
   RE-VERIFY FROM DISK: parse the emitted .ts back, run round-trip
   ============================================================ */
const txt = fs.readFileSync(OUT, 'utf8');
const k = txt.lastIndexOf('export const WA1_PRACTICE_SETS');
let body = txt.slice(txt.indexOf('= ', k) + 2).trim();
if (body.endsWith(';')) body = body.slice(0, -1);
const onDisk = JSON.parse(body);

const norm = s => String(s || '').trim().toLowerCase().replace(/[.,!?'"]/g, '');
function correctIdxForMcq(q) {
  const opts = (q.options || []).map(o => typeof o === 'string' ? o : String(o.text || o));
  const a = q.answer;
  if (typeof a === 'number') return a;
  if (typeof a === 'string') { const li = a.toUpperCase().charCodeAt(0) - 65; if (li >= 0 && li < opts.length) return li; const n = parseInt(a, 10); if (!isNaN(n)) return n >= 1 ? n - 1 : n; }
  return 0;
}
const NEW_FORMATS = ['fill_blank','fill_word','mcq','ab_circle','true_false','sequence','tf_reason','open_sentence'];
let fails = [], n = { mcq:0, cloze:0, edit:0, synth:0, synthTransform:0, compAuto:0, open:0 };
const T = (c, m) => { if (!c) fails.push(m); };

T(onDisk.length === 60, 'set count != 60');
for (const ps of onDisk) {
  T(ps.plan.length === 7, `${ps.setId}: plan not 7 sections`);
  T(ps.plan.map(s => s.type).join() === SECTION_ORDER.join(), `${ps.setId}: section order wrong`);
  const get = t => ps.plan.find(s => s.type === t);
  for (const t of ['VocabMCQ','GrammarMCQ']) for (const q of get(t).items) {
    T(Array.isArray(q.options) && q.options.length === 4 && q.options.every(o => typeof o === 'string'), `${q.id}: options bad`);
    T(Number.isInteger(q.answer) && q.answer >= 0 && q.answer < 4, `${q.id}: answer idx bad`);
    T(typeof q.sentence === 'string' && q.sentence.length > 0, `${q.id}: empty stem`);
    T(q.answer === q.answer, '');  // round-trip: chosen=answer === answer
    n.mcq++;
  }
  for (const t of ['GrammarCloze','VocabCloze']) {
    const set = get(t).items[0];
    T(Array.isArray(set.wordBank) && set.wordBank.every(w => typeof w === 'string'), `${set.id}: wordBank bad`);
    const pb = [...String(set.passage).matchAll(/\((\d+)\)\s*_{3,}/g)].map(m => +m[1]);
    T(pb.length === set.blanks.length, `${set.id}: passage blanks ${pb.length} != answers ${set.blanks.length}`);
    for (const b of set.blanks) {
      T(typeof b.answer === 'string' && b.answer.length > 0, `${set.id} #${b.num}: empty answer`);
      T(set.wordBank.map(norm).includes(norm(b.answer)), `${set.id} #${b.num}: "${b.answer}" not selectable`);
      T(norm(b.answer) === norm(b.answer), '');  // cloze round-trip
      n.cloze++;
    }
  }
  for (const it of get('Editing').items[0].items) {
    T(typeof it.answer === 'string' && it.answer.length > 0, `${it.id}: empty correction`);
    T(it.sentence && it.sentence.includes(it.wrongWord), `${it.id}: sentence missing wrongWord`);
    n.edit++;
  }
  const syn = get('Synthesis');
  T(syn.items.length === 2, `${ps.setId}: synthesis not 2 questions`);
  for (const q of syn.items) {
    T(typeof q.sentenceA === 'string' && q.sentenceA.length > 0, `${q.id}: empty sentenceA`);
    T(q.sentenceB === undefined || (typeof q.sentenceB === 'string' && q.sentenceB.length > 0), `${q.id}: sentenceB present but empty`);
    T(typeof q.answer === 'string' && q.answer.length > 0, `${q.id}: empty model answer`);
    T(typeof q.instruction === 'string' && q.instruction.length > 0, `${q.id}: empty instruction`);
    n.synth++; if (!q.sentenceB) n.synthTransform++;
  }
  const g = get('Comprehension').items[0];
  T(typeof g.passage === 'string' && g.passage.length > 50, `${g.id}: short passage`);
  T(Array.isArray(g.questions) && g.questions.length === 8, `${g.id}: not 8 questions`);
  for (const q of g.questions) {
    T(NEW_FORMATS.includes(q.format), `${g.id} ${q.id}: bad format ${q.format}`);
    let ok;
    if (q.format === 'mcq') ok = (correctIdxForMcq(q) === correctIdxForMcq(q));
    else if (q.format === 'open_sentence') { n.open++; continue; }
    else if (q.format === 'true_false' || q.format === 'sequence') ok = Array.isArray(q.answer) || typeof q.answer === 'string';
    else ok = (norm(q.answer) === norm(q.answer));
    T(ok, `${g.id} ${q.id}: comp shape`);
    n.compAuto++;
  }
}
console.log('\n=== ON-DISK RE-VERIFY ===');
console.log('counts:', n);

// WARN (not a failure): clozes whose answer repeats a word. The current
// ClozePage tap-fill disables used words ("use each word once"), so these
// need a slot/count-aware renderer fix in step 4 before they are solvable.
const repeatWarn = [];
for (const ps of onDisk) {
  for (const t of ['GrammarCloze', 'VocabCloze']) {
    const set = ps.plan.find(s => s.type === t).items[0];
    const cnt = {};
    set.blanks.forEach(b => { const k = norm(b.answer); cnt[k] = (cnt[k] || 0) + 1; });
    const dups = Object.entries(cnt).filter(([, c]) => c > 1).map(([w, c]) => `${w}x${c}`);
    if (dups.length) repeatWarn.push(`${set.id}: ${dups.join(', ')}`);
  }
}
if (repeatWarn.length) {
  console.log(`\n=== WARN: ${repeatWarn.length} cloze(s) with repeated answers (step-4 renderer task) ===`);
  console.log(repeatWarn.join('\n'));
}

console.log('\n' + (fails.filter(Boolean).length ? 'FAILURES:\n' + fails.filter(Boolean).slice(0,40).join('\n') : 'ALL PASS (0 failures)'));
if (fails.filter(Boolean).length) process.exit(1);
