// ============================================================================
// P3 Chinese Papers — Normalized Master Barrel Export
// src/data/p3/chinese/papers/index.ts
// Every entry is normalized to { meta, questions }.
// Passage text is preserved in meta when { passage, questions } sets exist.
// ============================================================================

// ── WA1 imports (7) ──
import rawWa12025 from './wa1/wa1_2025';
import rawWa1ChijRevision12025 from './wa1/wa1_chij_revision1_2025';
import rawWa1RedSwastika from './wa1/wa1_red_swastika';
import rawWa1RedswastikaMinirevision12025 from './wa1/wa1_redswastika_minirevision1_2025';
import rawWa1TaoNan2025 from './wa1/wa1_tao_nan_2025';
import rawWa1TaoNanMaintest2025 from './wa1/wa1_tao_nan_maintest_2025';
import rawWa1TaoNanSupplementary52025 from './wa1/wa1_tao_nan_supplementary5_2025';

// ── WA2 imports (17) ──
import rawRev2RedSwastikaHcl2024 from './wa2/rev2_red_swastika_hcl_2024';
import rawRev2StNicholasHcl2025 from './wa2/rev2_st_nicholas_hcl_2025';
import rawSupp2TaoNanHcl2024 from './wa2/supp2_tao_nan_hcl_2024';
import rawSupp5TaoNanHcl2023 from './wa2/supp5_tao_nan_hcl_2023';
import rawSuppTaoNanHcl22023 from './wa2/supp_tao_nan_hcl_2_2023';
import rawWa2CatholicHighHcl from './wa2/wa2_catholic_high_hcl';
import rawWa2MahaBodhiHcl2025 from './wa2/wa2_maha_bodhi_hcl_2025';
import rawWa2NanHuaHcl2023 from './wa2/wa2_nan_hua_hcl_2023';
import rawWa2NanHuaHcl2025 from './wa2/wa2_nan_hua_hcl_2025';
import rawWa2NanyangHcl from './wa2/wa2_nanyang_hcl';
import rawWa2NanyangHcl2024 from './wa2/wa2_nanyang_hcl_2024';
import rawWa2NanyangHcl2025 from './wa2/wa2_nanyang_hcl_2025';
import rawWa2PeiChunPublicHcl2025 from './wa2/wa2_pei_chun_public_hcl_2025';
import rawWa2PeiHwaPresbyterianHcl from './wa2/wa2_pei_hwa_presbyterian_hcl';
import rawWa2StNicholasHcl from './wa2/wa2_st_nicholas_hcl';
import rawWa3CatholicHighHcl from './wa2/wa3_catholic_high_hcl';
import rawWa3PeiChunPublicHcl2025 from './wa2/wa3_pei_chun_public_hcl_2025';

// ── WA3 imports (8) ──
import rawWa3ChijstnicholasRev32025 from './wa3/wa3_chijstnicholas_rev3_2025';
import rawWa3ChijstnicholasRev42025 from './wa3/wa3_chijstnicholas_rev4_2025';
import rawWa3PeichunTerm22025 from './wa3/wa3_peichun_term2_2025';
import rawWa3PeichunTerm32025 from './wa3/wa3_peichun_term3_2025';
import rawWa3RedswastikaRev32025 from './wa3/wa3_redswastika_rev3_2025';
import rawWa3TaonanSupp32024 from './wa3/wa3_taonan_supp3_2024';
import rawWa3TaonanSupp52025 from './wa3/wa3_taonan_supp5_2025';
import rawWa3TaonanWa32025 from './wa3/wa3_taonan_wa3_2025';

// ── EOY imports (18) ──
import rawEoyBodhiSchoolPaper22025 from './eoy/eoy_BodhiSchool_Paper2_2025';
import rawEoyCatholicHighPaper22025 from './eoy/eoy_CatholicHigh_Paper2_2025';
import rawEoyNanHuaPaper22025 from './eoy/eoy_NanHua_Paper2_2025';
import rawEoyAitongHigherPaper22025 from './eoy/eoy_aitong_higher_paper2_2025';
import rawEoyGongjiao2024Paper2 from './eoy/eoy_gongjiao_2024_paper2';
import rawEoyMahabodhiHigherPaper22025 from './eoy/eoy_mahabodhi_higher_paper2_2025';
import rawEoyNanhua2021Paper1 from './eoy/eoy_nanhua_2021_paper1';
import rawEoyNanhuaHclPaper22025 from './eoy/eoy_nanhua_hcl_paper2_2025';
import rawEoyNanhuaHigherPaper22025 from './eoy/eoy_nanhua_higher_paper2_2025';
import rawEoyNanyangHigherPaper22025 from './eoy/eoy_nanyang_higher_paper2_2025';
import rawEoyPeihwa2024Paper2 from './eoy/eoy_peihwa_2024_paper2';
import rawEoyPeiqun2021Paper2 from './eoy/eoy_peiqun_2021_paper2';
import rawEoyPuti2024Paper2 from './eoy/eoy_puti_2024_paper2';
import rawEoyRedswastikaHclRevision42025 from './eoy/eoy_redswastika_hcl_revision4_2025';
import rawEoyStnicholasHigherPaper22025 from './eoy/eoy_stnicholas_higher_paper2_2025';
import rawEoyTaonan2023Paper2 from './eoy/eoy_taonan_2023_paper2';
import rawEoyTaonan2024Paper2 from './eoy/eoy_taonan_2024_paper2';
import rawEoyTaonanHigherPaper22025 from './eoy/eoy_taonan_higher_paper2_2025';

export type NormalizedChinesePaper = {
  meta: Record<string, unknown>;
  questions: unknown[];
};

function buildFallbackMeta(sourceId: string): Record<string, unknown> {
  const [folder = "unknown", fileName = sourceId] = sourceId.split("/");
  const examLabel = folder.toUpperCase();
  const readableTitle = fileName.replace(/_/g, " ");
  return {
    title: `${readableTitle} (${examLabel})`,
    id: fileName,
    sourcePath: sourceId,
    assessment: examLabel,
    autoGenerated: true,
  };
}

function applyMetaFallback(
  meta: Record<string, unknown>,
  sourceId?: string,
): Record<string, unknown> {
  if (Object.keys(meta).length === 0 && sourceId) {
    return buildFallbackMeta(sourceId);
  }
  return meta;
}

function hasPassageQuestionsShape(value: unknown): value is {
  passage: string;
  questions: unknown[];
} {
  return (
    !!value &&
    typeof value === "object" &&
    typeof (value as { passage?: unknown }).passage === "string" &&
    Array.isArray((value as { questions?: unknown }).questions)
  );
}

function normalizePassageItem(item: unknown): unknown {
  if (!hasPassageQuestionsShape(item)) return item;

  const obj = item as Record<string, unknown>;
  const { passage, questions, meta: itemMeta, ...rest } = obj;
  const nestedMeta =
    itemMeta && typeof itemMeta === "object" && !Array.isArray(itemMeta)
      ? (itemMeta as Record<string, unknown>)
      : {};

  return {
    ...rest,
    meta: {
      ...nestedMeta,
      hasPassage: true,
      passageText: passage,
    },
    questions,
    passage,
  };
}

function normalizeQuestionsArray(questions: unknown[]): unknown[] {
  return questions.map(normalizePassageItem);
}

function flattenSectionValue(value: unknown): unknown[] {
  if (Array.isArray(value)) return normalizeQuestionsArray(value);
  if (hasPassageQuestionsShape(value)) {
    return [normalizePassageItem(value)];
  }
  if (value && typeof value === "object") {
    const section = value as { questions?: unknown[] };
    if (Array.isArray(section.questions)) {
      return normalizeQuestionsArray(section.questions);
    }
    return [value];
  }
  return [];
}

function extractQuestions(raw: Record<string, unknown>): unknown[] {
  if (hasPassageQuestionsShape(raw)) {
    return normalizeQuestionsArray(raw.questions);
  }
  if (Array.isArray(raw.questions)) return normalizeQuestionsArray(raw.questions);
  if (Array.isArray(raw.items)) return normalizeQuestionsArray(raw.items);
  if (Array.isArray(raw.sections)) {
    return (raw.sections as unknown[]).flatMap((section) =>
      flattenSectionValue(section),
    );
  }
  if (raw.sections && typeof raw.sections === "object") {
    return Object.values(raw.sections as Record<string, unknown>).flatMap(
      (section) => flattenSectionValue(section),
    );
  }
  return [];
}

function extractMeta(raw: Record<string, unknown>): Record<string, unknown> {
  let meta: Record<string, unknown>;

  if (raw.meta && typeof raw.meta === "object" && !Array.isArray(raw.meta)) {
    meta = { ...(raw.meta as Record<string, unknown>) };
  } else {
    const { questions, items, sections, passage, ...rest } = raw;
    meta = { ...rest };
  }

  if (typeof raw.passage === "string") {
    meta = {
      ...meta,
      hasPassage: true,
      passageText: raw.passage,
    };
  }

  return meta;
}

export function normalizePaper(
  raw: unknown,
  sourceId?: string,
): NormalizedChinesePaper {
  if (Array.isArray(raw)) {
    return {
      meta: applyMetaFallback(
        sourceId ? buildFallbackMeta(sourceId) : { title: "Unknown Paper", autoGenerated: true },
        sourceId,
      ),
      questions: normalizeQuestionsArray(raw),
    };
  }

  const data = (raw ?? {}) as Record<string, unknown>;

  if (hasPassageQuestionsShape(data)) {
    return {
      meta: applyMetaFallback(extractMeta(data), sourceId),
      questions: normalizeQuestionsArray(data.questions),
    };
  }

  return {
    meta: applyMetaFallback(extractMeta(data), sourceId),
    questions: extractQuestions(data),
  };
}

export const p3ChineseWA1Papers: NormalizedChinesePaper[] = [
  normalizePaper(rawWa12025, 'wa1/wa1_2025'),
  normalizePaper(rawWa1ChijRevision12025, 'wa1/wa1_chij_revision1_2025'),
  normalizePaper(rawWa1RedSwastika, 'wa1/wa1_red_swastika'),
  normalizePaper(rawWa1RedswastikaMinirevision12025, 'wa1/wa1_redswastika_minirevision1_2025'),
  normalizePaper(rawWa1TaoNan2025, 'wa1/wa1_tao_nan_2025'),
  normalizePaper(rawWa1TaoNanMaintest2025, 'wa1/wa1_tao_nan_maintest_2025'),
  normalizePaper(rawWa1TaoNanSupplementary52025, 'wa1/wa1_tao_nan_supplementary5_2025'),
];

export const p3ChineseWA2Papers: NormalizedChinesePaper[] = [
  normalizePaper(rawRev2RedSwastikaHcl2024, 'wa2/rev2_red_swastika_hcl_2024'),
  normalizePaper(rawRev2StNicholasHcl2025, 'wa2/rev2_st_nicholas_hcl_2025'),
  normalizePaper(rawSupp2TaoNanHcl2024, 'wa2/supp2_tao_nan_hcl_2024'),
  normalizePaper(rawSupp5TaoNanHcl2023, 'wa2/supp5_tao_nan_hcl_2023'),
  normalizePaper(rawSuppTaoNanHcl22023, 'wa2/supp_tao_nan_hcl_2_2023'),
  normalizePaper(rawWa2CatholicHighHcl, 'wa2/wa2_catholic_high_hcl'),
  normalizePaper(rawWa2MahaBodhiHcl2025, 'wa2/wa2_maha_bodhi_hcl_2025'),
  normalizePaper(rawWa2NanHuaHcl2023, 'wa2/wa2_nan_hua_hcl_2023'),
  normalizePaper(rawWa2NanHuaHcl2025, 'wa2/wa2_nan_hua_hcl_2025'),
  normalizePaper(rawWa2NanyangHcl, 'wa2/wa2_nanyang_hcl'),
  normalizePaper(rawWa2NanyangHcl2024, 'wa2/wa2_nanyang_hcl_2024'),
  normalizePaper(rawWa2NanyangHcl2025, 'wa2/wa2_nanyang_hcl_2025'),
  normalizePaper(rawWa2PeiChunPublicHcl2025, 'wa2/wa2_pei_chun_public_hcl_2025'),
  normalizePaper(rawWa2PeiHwaPresbyterianHcl, 'wa2/wa2_pei_hwa_presbyterian_hcl'),
  normalizePaper(rawWa2StNicholasHcl, 'wa2/wa2_st_nicholas_hcl'),
  normalizePaper(rawWa3CatholicHighHcl, 'wa2/wa3_catholic_high_hcl'),
  normalizePaper(rawWa3PeiChunPublicHcl2025, 'wa2/wa3_pei_chun_public_hcl_2025'),
];

export const p3ChineseWA3Papers: NormalizedChinesePaper[] = [
  normalizePaper(rawWa3ChijstnicholasRev32025, 'wa3/wa3_chijstnicholas_rev3_2025'),
  normalizePaper(rawWa3ChijstnicholasRev42025, 'wa3/wa3_chijstnicholas_rev4_2025'),
  normalizePaper(rawWa3PeichunTerm22025, 'wa3/wa3_peichun_term2_2025'),
  normalizePaper(rawWa3PeichunTerm32025, 'wa3/wa3_peichun_term3_2025'),
  normalizePaper(rawWa3RedswastikaRev32025, 'wa3/wa3_redswastika_rev3_2025'),
  normalizePaper(rawWa3TaonanSupp32024, 'wa3/wa3_taonan_supp3_2024'),
  normalizePaper(rawWa3TaonanSupp52025, 'wa3/wa3_taonan_supp5_2025'),
  normalizePaper(rawWa3TaonanWa32025, 'wa3/wa3_taonan_wa3_2025'),
];

export const p3ChineseEOYPapers: NormalizedChinesePaper[] = [
  normalizePaper(rawEoyBodhiSchoolPaper22025, 'eoy/eoy_BodhiSchool_Paper2_2025'),
  normalizePaper(rawEoyCatholicHighPaper22025, 'eoy/eoy_CatholicHigh_Paper2_2025'),
  normalizePaper(rawEoyNanHuaPaper22025, 'eoy/eoy_NanHua_Paper2_2025'),
  normalizePaper(rawEoyAitongHigherPaper22025, 'eoy/eoy_aitong_higher_paper2_2025'),
  normalizePaper(rawEoyGongjiao2024Paper2, 'eoy/eoy_gongjiao_2024_paper2'),
  normalizePaper(rawEoyMahabodhiHigherPaper22025, 'eoy/eoy_mahabodhi_higher_paper2_2025'),
  normalizePaper(rawEoyNanhua2021Paper1, 'eoy/eoy_nanhua_2021_paper1'),
  normalizePaper(rawEoyNanhuaHclPaper22025, 'eoy/eoy_nanhua_hcl_paper2_2025'),
  normalizePaper(rawEoyNanhuaHigherPaper22025, 'eoy/eoy_nanhua_higher_paper2_2025'),
  normalizePaper(rawEoyNanyangHigherPaper22025, 'eoy/eoy_nanyang_higher_paper2_2025'),
  normalizePaper(rawEoyPeihwa2024Paper2, 'eoy/eoy_peihwa_2024_paper2'),
  normalizePaper(rawEoyPeiqun2021Paper2, 'eoy/eoy_peiqun_2021_paper2'),
  normalizePaper(rawEoyPuti2024Paper2, 'eoy/eoy_puti_2024_paper2'),
  normalizePaper(rawEoyRedswastikaHclRevision42025, 'eoy/eoy_redswastika_hcl_revision4_2025'),
  normalizePaper(rawEoyStnicholasHigherPaper22025, 'eoy/eoy_stnicholas_higher_paper2_2025'),
  normalizePaper(rawEoyTaonan2023Paper2, 'eoy/eoy_taonan_2023_paper2'),
  normalizePaper(rawEoyTaonan2024Paper2, 'eoy/eoy_taonan_2024_paper2'),
  normalizePaper(rawEoyTaonanHigherPaper22025, 'eoy/eoy_taonan_higher_paper2_2025'),
];

export const allP3ChinesePapers = {
  wa1: p3ChineseWA1Papers,
  wa2: p3ChineseWA2Papers,
  wa3: p3ChineseWA3Papers,
  eoy: p3ChineseEOYPapers,
};
