// ============================================================
// P3 Higher Chinese – EOY Past Papers Index
// Auto-generated by Genius Project data pipeline
// Schools covered in this batch:
//   - Tao Nan School (2023, 2024)
//   - Nan Hua Primary School (2021 revision)
//   - Pei Chun Public School (2021)
//   - Pei Hwa Presbyterian Primary School (2024)
//   - Catholic High (Gong Jiao) Attached Primary (2024)
//   - Bodhi School / Puti (2024)
// ============================================================

export { default as eoyTaoNan2023Paper2 } from './eoy_taonan_2023_paper2';
export { default as eoyNanHua2021Paper1 }  from './eoy_nanhua_2021_paper1';
export { default as eoyPeiQun2021Paper2 }  from './eoy_peiqun_2021_paper2';
export { default as eoyPeiHwa2024Paper2 }  from './eoy_peihwa_2024_paper2';
export { default as eoyTaoNan2024Paper2 }  from './eoy_taonan_2024_paper2';
export { default as eoyGongJiao2024Paper2 } from './eoy_gongjiao_2024_paper2';
export { default as eoyPuti2024Paper2 }    from './eoy_puti_2024_paper2';
